apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secret
type: Opaque
stringData:
  SUPABASE_URL: https://jkfymuwtwvsallcrniuh.supabase.co
  SUPABASE_KEY: sb_publishable_SiySoStSiPvy5Vzd47KP6g_Tk3Gosb_
