apiVersion: v1
kind: Service
metadata:
  name: shopflow-lite-service
  labels:
    app: shopflow-lite
spec:
  type: NodePort
  selector:
    app: shopflow-lite
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
      name: http
